# Generated by Django 4.2.2 on 2024-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Worn', 'Worn')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='material',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('polyester', 'Polyester'), ('linen', 'Linen'), ('wool', 'Wool'), ('silk', 'Silk'), ('denim', 'Denim'), ('leather', 'Leather'), ('nylon', 'Nylon')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='pattern',
            field=models.CharField(choices=[('Horizontal Stripes', 'Horizontal Stripes'), ('Vertical Stripes', 'Vertical Stripes'), ('Checkered', 'Checkered'), ('Graphic Print', 'Graphic Print')], default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Jacket', 'Jacket'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes')], default=False, max_length=255),
            preserve_default=False,
        ),
    ]
