# Generated by Django 4.2.2 on 2024-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image_color_image_condition_image_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
